CREATE TABLE `Cliente` (
	`Login` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Telefone` INTEGER,
	`Nome` VARCHAR(255),
	`Senha` INTEGER,
	`Sobrenome` VARCHAR(255),
	`Email` VARCHAR(255),
	`ID_Endereco` INTEGER,
	`ID_Car` INTEGER,
	PRIMARY KEY(`Login`)
);


CREATE TABLE `Endereco` (
	`ID_Endereco` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Logradouro` VARCHAR(255),
	`Cidade` VARCHAR(255),
	`Estado` VARCHAR(255),
	PRIMARY KEY(`ID_Endereco`)
);


CREATE TABLE `Carrinho` (
	`ID_Car` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Tipo` VARCHAR(255),
	`Preco_total` NUMERIC,
	`ID_Data` INTEGER,
	`ID_List` INTEGER,
	PRIMARY KEY(`ID_Car`)
);


CREATE TABLE `Data` (
	`ID_Data` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Dia` INTEGER,
	`Mes` INTEGER,
	`Ano` INTEGER,
	PRIMARY KEY(`ID_Data`)
);


CREATE TABLE `Lista_de_Itens` (
	`ID_List` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Preco` NUMERIC,
	`Quantidade` INTEGER,
	`Cod_Prod` INTEGER,
	PRIMARY KEY(`ID_List`)
);


CREATE TABLE `Estoque` (
	`Cod_Prod` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Quant_Est` INTEGER,
	`Cor` VARCHAR(255),
	`Tamanho` NUMERIC,
	PRIMARY KEY(`Cod_Prod`)
);


CREATE TABLE `Produto` (
	`Cod_Prod` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Nome_Prod` VARCHAR(255),
	`Preco` NUMERIC,
	`Figura` TINYBLOB,
	`Preco` NUMERIC,
	`ID_Cat` INTEGER,
	PRIMARY KEY(`Cod_Prod`)
);


CREATE TABLE `Categoria` (
	`ID_Cat` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Descricao_Cat` VARCHAR(255),
	PRIMARY KEY(`ID_Cat`)
);


ALTER TABLE `Carrinho`
ADD FOREIGN KEY(`ID_Data`) REFERENCES `Data`(`ID_Data`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Cliente`
ADD FOREIGN KEY(`ID_Endereco`) REFERENCES `Endereco`(`ID_Endereco`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Cliente`
ADD FOREIGN KEY(`ID_Car`) REFERENCES `Carrinho`(`ID_Car`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Lista_de_Itens`
ADD FOREIGN KEY(`ID_List`) REFERENCES `Carrinho`(`ID_List`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Estoque`
ADD FOREIGN KEY(`Cod_Prod`) REFERENCES `Lista_de_Itens`(`Cod_Prod`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Produto`
ADD FOREIGN KEY(`Cod_Prod`) REFERENCES `Estoque`(`Cod_Prod`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Categoria`
ADD FOREIGN KEY(`ID_Cat`) REFERENCES `Produto`(`ID_Cat`)
ON UPDATE NO ACTION ON DELETE NO ACTION;